### ISSUE TITLE
Work through deploying AVD via MSFT's automation solution

### ISSUE THREAD

**Issue by sandman-battelle** [battelle-cube/azure-avd-automation#1]

**Comment by valerio-battelle** [comment]
# Steps taken prior to deployment

1. Created a virtual network named "*aadds-vnet*" in the "*rg-aad-domain-services*" resource group.  Peering is setup on this network with the remote vnet ID `/subscriptions/28a876f8-a699-4a31-a85a-daa072d7a496/resourceGroups/rg-aad-domain-services/providers/Microsoft.Network/virtualNetworks/aadds-vnet`.  This is the domain service network named "*aadds-vnet*" in the "*cit - Identity*" subscription.  
2. Created the "*avd_users*" Security Group in ADDS.
3. Updated several json files with Battelle specific values.  These changes are captured in [this ](https://github.com/battelle-cube/azure-avd-automation/commit/91c901dd256adf88c4c99ad7d3b37bcbba630cb2)commit.

# Deployment 
- Command
`az deployment sub create --location usgovvirginia --template-file .\solutions\avd\solution.json`

# Problems with deployment
- For some reason the script fails attempting to join created VM's to the Battelle domain.  After I manually joined the VM's to the domain I executed the deployment command again and it completed successfully

**Comment by sandman-battelle** [comment]
Need `User Access Administrator` on the subscription

**Comment by valerio-battelle** [comment]
Got to Azure Active Dircetory and add users to the `avd_users` group that need access to AVD and go [here](https://rdweb.wvd.azure.us/arm/webclient/index.html) to connect to AVD

**Comment by sandman-battelle** [comment]
Merged up to latest commit from @jamasten

**Comment by sandman-battelle** [comment]
_Note: https://github.com/battelle-cube/azure-avd-automation/commit/562ec6e5ee082529d23d8821908c8d7f4f35dc88 was removed by `push -f`_

**Comment by valerio-battelle** [comment]
If deployed in "subscription1" and you want to deploy it to different subscription, you must delete the Custom Role named `StartVmOnConnect` from "subscription1" before running the avd solution.

**Comment by sandman-battelle** [comment]
Custom roles may need to move to the CUBE Management Group level 'cause it seems like there-can-be-only-one??

**Comment by jamasten** [comment]
Yes, if using multiple subscriptions for AVD, you would want to bump this up to the MGMT group level.  It would be easier to make the role and assignment at the management group scope manually than trying to rework that change into the code.

**Comment by sandman-battelle** [comment]
@jamasten Thanks for chiming in here.  Is nice to know the teacher is watching ;)
