### ISSUE TITLE
Multiple Deployments of AVD Solution

### ISSUE THREAD

**Issue by valerio-battelle** [battelle-cube/azure-avd-automation#3]
Deploying the AVD Solution to multiple subscriptions fails with the 2 different errors.  The first issue is the "RoleDefinitionWithSameNameExists " error and seems to be caused by the role definition "StartVmOnConnect" not being able to exist in multiple subscriptions.   The second issue is the "ResourceDeploymentFailure" error.  This error can be reproduced by successfully deploying AVD into one subscription then deploy ADV to a different subscription.   

- [x] RoleDefinitionWithSameNameExists - A role definition cannot be updated with a name that already exists.
- [x] ResourceDeploymentFailure - Tenant ID, application ID, principal ID, and scope are not allowed to be updated.
- [ ] Update to use `cube-core` (see battelle-cube/cube-program#86)

**Comment by sandman-battelle** [comment]
I’ve merged the new changes from Jason and PR’d in our multiple deployments branch.  Everything is on main (is called master in this repo, we should fix that) and needs tested.
