### ISSUE TITLE
Updates to variable descriptions

### ISSUE THREAD

**Issue by valerio-battelle** [battelle-cube/azure-avd-automation#55]
Update "AllowedValues":
In [solution.json](https://github.com/battelle-cube/terraform-cube-avd/blob/main/solutions/avd/solution.json) the following parameters have allowedValues defined: DiskSku, DomainServices, FSLogixStorage, HostPoolType, KerberosEncryption, LogAnalyticsWorkspaceSku.  These values should be added to the description for the corresponding TF variables in [main.tf](https://github.com/battelle-cube/terraform-cube-avd/blob/main/main.tf) so that they are displayed in the [TFE module input description](https://tfe-prd.battelle.io/app/battelle/registry/modules/private/battelle/avd/cube/0.0.16?tab=inputs)

Also, add resource name suffix character limit to module variable description

**Comment by sandman-battelle** [comment]
obsolete repo
